import type { NextPage } from 'next';
import Head from 'next/head';
import { css } from '@emotion/css';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Routines</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <p
          className={css`
            font-weight: 800;
            font-size: 64px;
            letter-spacing: -0.04em;
          `}
        >
          Routines
        </p>
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;
